<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName>iKun</AssemblyName>
    <RootNamespace>me.cqp.luohuaming.iKun</RootNamespace>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>

  <ItemGroup>
    <None Remove=".gitattributes" />
    <None Remove=".gitignore" />
    <None Remove="llms.txt" />
    <None Remove="README.md" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Another-Mirai-Native.Abstractions" Version="1.2.4" />
    <PackageReference Include="SqlSugarCore" Version="5.1.4.211" />
	  <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.11" />
	  <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.13" />
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	  <PackageReference Include="NLog" Version="5.3.4" />
  </ItemGroup>

</Project>
